# @file
#
# Main package configuration of Rust-UCI(RUCI).
# SPDX-License-Identifier: WTFPL

[package]
name = "ruci"
version = "0.1.0"
edition = "2021"

[dependencies]
cgi = "0.6.0"
rust-uci = { git = 'https://github.com/East-China-Gold-Medal/rust-uci' }
lazy_static = "1.5.0"
